name: yml New prepare-dataset curation
description: When a new MS is added to the prepare dataset list
title: "<Include MS Submission ID, Dataset DOI number, userbox, name/ID, curator name in title>"
labels: 
body:
- type: checkboes
  attributes:
    labvel:Userbox name is provided in ticket title
    options:
    - label: I have included the userbox name in the ticket title
      required: true
 
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
