name: Bug Report
description: File a bug report.
title: "[Include MS Submission ID, Dataset DOI number, userbox]"
labels: ["datasetPrep"]
projects: ["gigascience/87"]
body:
  - type: markdown
    attributes:
      value: |
        Fill out the form with the manuscript and dataset info!
  - type: textarea
    id: checklist
    attributes:
      label: Checklist
      description: Please complete the boxes to confirm each of the checklist items have been done, you can add additional comments here
      placeholder: ex. any additional infor provided by Eds at handover
    validations:
      required: false
  - type: input
    id: ms-sub-id
    attributes:
      label: MS Submission ID
      description: Add the manuscript submission ID here
      placeholder: GIGA-D-25-00123
    validations:
      required: true
  - type: input
    id: ms-title
    attributes:
      label: MS title
      description: Add the manuscript title here
      placeholder: 
      value: "Supporting data for "
    validations:
      required: true
  - type: textarea
    id: ms-author
    attributes:
      label: MS Author
      description: Add the manuscript contact author(s) here, you can include name, email and orcid.
      placeholder: 
    validations:
      required: false      
  - type: dropdown
    id: handling-editor
    attributes:
      label: Handling Editor
      description: Select the name of the Handling editor
      options:
        - unknown (Default)
        - Scott
        - Nicole
        - Hans
        - Hongling
        - Hongfang
        - Qing
      default: 0
    validations:
      required: true
  - type: input
    id: dropbox-id
    attributes:
      label: user-dropbox details
      description: Provide the user-dropbox name and login details.
      placeholder: eg. userNNN:abc123def
    validations:
      required: true
  - type: checkboxes
    id: pre-filled-spreadsheet-checks
    attributes:
      label: Please check the boxes to confirm each of the following items have been checked on the pre-filled spreadsheet
      options:
        - label: Checked if user email address is already in GigaDB
          required: true
        - label: Dataset type(s) are spelt correctly 
          required: true
        - label: Author list format is as expected
          required: true
        - label: Funding details are formated correctly with no additional commas or semi-colons
          required: true
  - type: textarea
    id: spreadsheet
    attributes:
      label: pre-filled Spreadsheet
      description: Please upload the pre-filled spreadsheet here. You can attach files by clicking this area to highlight it and then dragging files into it.
    validations:  
      required: true
